add badge

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -25,4 +25,10 @@ jobs:
       run: go build -v ./...
 
     - name: Test
-      run: go test -v ./...
+      run: |
+            go test -v ./...
+            if [ $? -ne 0 ]; then
+              echo "Tests failed"
+              exit 1
+            fi
+  
